---
title: "tximport_example"
author: "adowneywall"
date: "5/12/2019"
output: 
  html_document: 
    keep_md: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tximportData)
library(tximport)
library(readr)
```

Basic Options
```{r}
dir <- system.file("extdata", package = "tximportData")
list.files(dir)

samples <- read.table(file.path(dir, "samples.txt"), header = TRUE)
samples

files <- file.path(dir, "salmon", samples$run, "quant.sf.gz")
names(files) <- paste0("sample", 1:6)
all(file.exists(files))


tx2gene <- read_csv(file.path(dir, "tx2gene.gencode.v27.csv"))
head(tx2gene)

txi <- tximport(files, type = "salmon", tx2gene = tx2gene)
names(txi)
```
  
Rerun with gibs sampler options from salmon  
```{r}
files <- file.path(dir, "salmon_gibbs", samples$run, "quant.sf")
all(file.exists(files))

names(files) <- paste0("sample", 1:6)
txi.inf.rep <- tximport(files, type = "salmon", txOut = TRUE)
names(txi.inf.rep)

```