---
title: "05 Salmon WGCNA"
author: "adowneywall"
date: "5/13/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(WGCNA)
```

**Data**
```{r}
gc <- readRDS("/home/downeyam/Github/2017OAExp_Oysters/input_files/salmon_RNA/run20180512_gene_abundMatrix_.RData")
gc <- readRDS("/home/downeyam/Github/2017OAExp_Oysters/input_files/salmon_RNA/run20180512_gene_countMatrix_.RData")
gc <- gc[-c(1:205),] #removing some no LOC genes (most trna)
gc_t <- t(gc)
    
gsg <-  goodSamplesGenes(gc_t, verbose = 3)

gsg$allOK

if (!gsg$allOK){# Optionally, print the gene and sample names that were removed:
  if (sum(!gsg$goodGenes)>0){
    printFlush(paste("Removing genes:", paste(colnames(gc_t)[!gsg$goodGenes], collapse = ", ")))
  }
  if (sum(!gsg$goodSamples)>0){
    printFlush(paste("Removing samples:", paste(rownames(gc_t)[!gsg$goodSamples], collapse = ", ")))
  }
  # Remove the offending genes and samples from the data:
  datExpr = gc_t[gsg$goodSamples, gsg$goodGenes]
}
gsg <-  goodSamplesGenes(datExpr, verbose = 3)
gsg$allOK
```

```{r}
model<-read.csv("/home/downeyam/Github/2017OAExp_Oysters/input_files/RNA/metadata_cvirginica_rna_meta.txt", header=TRUE)
model$Treatment <- as.factor(model$treatment)
model$Time <- as.character(model$timepoint)
model$Time[model$Time == "3"] <- "09"
model$Time[model$Time == "6"] <- "80"
model$Time <- as.factor(model$Time)
model$Pop <- as.factor(model$population)
model$Lane <- as.factor(model$lane)
model$SFV <-  interaction(model$Time,model$Treatment) # Creates single factor variable for combination of time and treatment
model2 <- dplyr::select(model,c("sample_name","Time","Treatment","epf_pH","env_pH","dry_wgtcorr"))
model2$Time <- as.character(model2$Time)
model2$Treatment <- as.character((model2$Treatment))
model2$Time[model2$Time == "09"] <- "0"
model2$Time[model2$Time == "80"] <- "1"
model2$Treatment[model2$Treatment == "400"] <- "0"
model2$Treatment[model2$Treatment == "2800"] <- "1"
model2$Time <- as.numeric(model2$Time)
model2$Treatment <- as.numeric(model2$Treatment)

wg_model <- model2[,-1]
row.names(wg_model) <- model2[,1]
```

```{r}
save(datExpr, wg_model, file = "/home/downeyam/Github/2017OAExp_Oysters/results/20180513_salmonrun_consensus.RData")
```

## After running consensus on auto R script on cluster
```{r}
#net = load("/home/downeyam/Github/2017OAExp_Oysters/results/WGCNA/20180513_SalmonRun_network_auto.RData")
net = load("/home/downeyam/Github/2017OAExp_Oysters/results/WGCNA/20180513_SalmonRun_networkv2_auto.RData")

mergedColors = labels2colors(moduleLabels)
plotDendroAndColors(geneTree,
                    "Module colors",dendroLabels = FALSE, hang = 0.03,
                    addGuide = TRUE, guideHang = 0.05)
```

```{r}
nGenes = ncol(datExpr);
nSamples = nrow(datExpr);
MEs0 = moduleEigengenes(datExpr, moduleColors)$eigengenes
MEs = orderMEs(MEs0)
moduleTraitCor = cor(MEs, wg_model, use = "p");
moduleTraitPvalue = corPvalueStudent(moduleTraitCor, nSamples);
```

```{r}
sizeGrWindow(10,6)
textMatrix = paste(signif(moduleTraitCor, 2), "\n(",signif(moduleTraitPvalue, 1), ")", sep = "");
dim(textMatrix) = dim(moduleTraitCor)
par(mar = c(6, 8.5, 3, 3))
labeledHeatmap(Matrix = moduleTraitCor,
               xLabels = names(wg_model),
               yLabels = names(MEs),
               ySymbols = names(MEs),
               colorLabels = FALSE,
               colors = blueWhiteRed(50),
               textMatrix = textMatrix,
               setStdMargins = FALSE,
               cex.text = 0.25, yColorWidth = c(.1),
               cex.lab.y = 0.6,
               zlim = c(-1,1),
               main = paste("Module-Variable relationships"))
```
