---
title: "STAR Pipeline ReRun Comparison"
author: "adowneywall"
date: "4/24/2019"
output: 
  html_document:
    keep_md: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

```{r echo=FALSE}
# Original count Matrix
GeneCounts <- read.delim("~/Github/2017OAExp_Oysters/results/C_virginica_gene_count_final.txt",header=TRUE,sep="",row.names=1)
# Just th counts from a rerun of sample 17005 
newCount <- read.delim("/home/downeyam/Desktop/17005_exon_count.txt",header=FALSE,sep="",row.names=1)
newCount$LOC <- row.names(newCount)

# Subset original full data for just sample 17005
smallCount <- data.frame(GeneCounts$RNA17005)
smallCount$LOC <- row.names(GeneCounts)

# Merge the two runs together
merged <- merge(newCount,smallCount,by = "LOC")
merged$diff <-  merged$V3-merged$GeneCounts.RNA17005
```

### Simple Descriptive Stats  

Number of Counts in Original Run
```{r}
sum(smallCount$GeneCounts.RNA17005)
```

Number of Counts in Rerun
```{r echo=FALSE}
sum(newCount$V3[!is.na(newCount$V3)])
```

**Wow over 100k more counts in the rerun**

### Plots  

**Looking at ALL loci**
```{r}
# 
plot(merged$diff[order(merged$diff)]~ 
       seq(0,1, length=39003),ylim=c(-50,25),type="l",xlab="Cumulative Proportion",ylab="Gene Counts (black line = Difference, red dots = -(original count))")
points(c(-(merged$GeneCounts.RNA17005[order(merged$diff)])-10)~
         seq(0,1, length=39003),col="red",lwd=.2)
abline(h=5,col="green")
abline(v=((39003-sum(merged$diff > 5))/39003),col="green")
abline(h=10,col="blue")
abline(v=((39003-sum(merged$diff > 10))/39003),col="blue")
```
  
**Just those with positive difference in the upper 5%**  
```{r}
plot(merged$diff[order(merged$diff)]~ 
       seq(0,1, length=39003),ylim=c(-200,25),xlim=c(0,0.05),type="l",
     xlab="Cumulative Proportion",ylab="Gene Counts (black line = Difference, red dots = -(original count))")
points(c(-(merged$GeneCounts.RNA17005[order(merged$diff)])-10)~
         seq(0,1, length=39003),col="red",lwd=.25)
```

**Just those with negative difference in the lower 5%**  
```{r}
plot(merged$diff[order(merged$diff)]~ 
       seq(0,1, length=39003),ylim=c(-5000,5000),xlim=c(.95,1),type="l",
     xlab="Cumulative Proportion",ylab="Gene Counts (black line = Difference, red dots = -(original count))")
points(c(-(merged$GeneCounts.RNA17005[order(merged$diff)])-10)~
         seq(0,1, length=39003),col="red",lwd=.25)
```
