---
title: "05 Salmon WGCNA"
author: "adowneywall"
date: "5/13/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(WGCNA)
```

**Data**
```{r}
gc <- readRDS("/home/downeyam/Github/2017OAExp_Oysters/input_files/RNA/salmon_pipeline/run20190610_counts/geneMatrixAbundance_default.RData")
gc_t <- t(gc)
gsg <-  goodSamplesGenes(gc_t, verbose = 3)
gsg$allOK
  
if (!gsg$allOK){# Optionally, print the gene and sample names that were removed:
  if (sum(!gsg$goodGenes)>0){
    printFlush(paste("Removing genes:", paste(colnames(gc_t)[!gsg$goodGenes], collapse = ", ")))
  }
  if (sum(!gsg$goodSamples)>0){
    printFlush(paste("Removing samples:", paste(rownames(gc_t)[!gsg$goodSamples], collapse = ", ")))
  }
  # Remove the offending genes and samples from the data:
  datExpr = gc_t[gsg$goodSamples, gsg$goodGenes]
}  
gsg <-  goodSamplesGenes(datExpr, verbose = 3)
gsg$allOK
```

```{r}
model<-read.csv("/home/downeyam/Github/2017OAExp_Oysters/input_files/RNA/metadata_cvirginica_rna_meta.csv", header=TRUE)
model$Treatment <- as.factor(model$treatment)
model$Time <- as.character(model$timepoint)
model$Time[model$Time == "3"] <- "09"
model$Time[model$Time == "6"] <- "80"
model$Time <- as.factor(model$Time)
model$Pop <- as.factor(model$population)
model$Lane <- as.factor(model$lane)
names(model)
model$SFV <-  interaction(model$Time,model$Treatment) # Creates single factor variable for combination of time and treatment
model2 <- dplyr::select(model,c("sample_name","Time","Treatment",
                                "D9_C","D9_E","D80_C","D80_E",
                                "epf_pH","HN_Condition","Simple_Condition"))
model2$Time <- as.character(model2$Time)
model2$Treatment <- as.character((model2$Treatment))
model2$D9_C <- as.numeric(model2$D9_C)
model2$D9_E <- as.numeric(model2$D9_E)
model2$D80_C <- as.numeric(model2$D80_C)
model2$D80_E <- as.numeric(model2$D80_E)
model2$Time[model2$Time == "09"] <- "0"
model2$Time[model2$Time == "80"] <- "1"
model2$Treatment[model2$Treatment == "400"] <- "0"
model2$Treatment[model2$Treatment == "2800"] <- "1"
model2$Time <- as.numeric(model2$Time)
model2$Treatment <- as.numeric(model2$Treatment)

wg_model <- model2[,-1]
row.names(wg_model) <- model2[,1]
```

```{r}
save(datExpr, wg_model, file = "/home/downeyam/Github/2017OAExp_Oysters/results/20190610_WCGNA_salmonrun_gene_consensus.RData")
```

## After running consensus on auto R script on cluster
```{r}
#net = load("/home/downeyam/Github/2017OAExp_Oysters/results/WGCNA/20180513_SalmonRun_network_auto.RData")
net = load("/home/downeyam/Github/2017OAExp_Oysters/results/WGCNA/20190610_SalmonRun_gene_network_auto.RData")
str(datExpr)
mergedColors = labels2colors(moduleLabels)
plotDendroAndColors(geneTree,
                    "Module colors",dendroLabels = FALSE, hang = 0.03,
                    addGuide = TRUE, guideHang = 0.05)
```

```{r}
nGenes = ncol(datExpr);
nSamples = nrow(datExpr);
MEs0 = moduleEigengenes(datExpr, moduleColors)$eigengenes
MEs = orderMEs(MEs0)
moduleTraitCor = cor(MEs, wg_model, use = "p");
moduleTraitPvalue = corPvalueStudent(moduleTraitCor, nSamples);
```

```{r}
sizeGrWindow(10,6)
textMatrix = paste(signif(moduleTraitCor, 2), "\n(",signif(moduleTraitPvalue, 1), ")", sep = "");
dim(textMatrix) = dim(moduleTraitCor)
par(mar = c(6, 8.5, 3, 3))
str(moduleTraitCor)
labeledHeatmap(Matrix = moduleTraitCor,
               xLabels = names(wg_model),
               yLabels = names(MEs),
               #ySymbols = names(MEs),
               colorLabels = FALSE,
               colors = blueWhiteRed(50),
               #textMatrix = textMatrix,
               setStdMargins = FALSE,
               cex.text = 0.4, yColorWidth = c(.1),
               cex.lab.y = 0.6,
               zlim = c(-1,1),
               main = paste("Module-Variable relationships"))

module_R <- cbind(modules=names(MEs),signif(moduleTraitCor, 2))
module_p <- cbind(modules=names(MEs),signif(moduleTraitPvalue,1))

length(module_R[,1])
#Treatment
length(module_p[module_p[,3]<0.05,1])
1/49
#Time
length(module_p[module_p[,2]<0.05,1])
4/49
#D9_C
length(module_p[module_p[,4]<0.05,1])
1/49
#D9_E
length(module_p[module_p[,5]<0.05,1])
2/49
#D80_C
length(module_p[module_p[,6]<0.05,1])
5/49
#D80_E
length(module_p[module_p[,7]<0.05,1])
2/49
#epf_ph
length(module_p[module_p[,8]<0.05,1])
1/49
#HN_Condition
length(module_p[module_p[,9]<0.05,1])
2/49
#Simple_Condition
length(module_p[module_p[,10]<0.05,1])
4/49
```

Specific Modules
```{r}
# Define variable weight containing the weight column of datTrait
weight = as.data.frame(wg_model$epf_pH)
names(weight) = "epf_pH"
# names (colors) of the modules
modNames = substring(names(MEs), 3)
geneModuleMembership = as.data.frame(cor(datExpr, MEs, use = "p"))
MMPvalue = as.data.frame(corPvalueStudent(as.matrix(geneModuleMembership), nSamples))
names(geneModuleMembership) = paste("MM", modNames, sep="");names(MMPvalue) = paste("p.MM", modNames, sep="")
geneTraitSignificance = as.data.frame(cor(datExpr, weight, use = "p"))
GSPvalue = as.data.frame(corPvalueStudent(as.matrix(geneTraitSignificance), nSamples))
names(geneTraitSignificance) = paste("GS.", names(weight), sep="");names(GSPvalue) = paste("p.GS.", names(weight), sep="");
module = "orangered4"
column = match(module, modNames)
moduleGenes = moduleColors==module
sizeGrWindow(7, 7);par(mfrow = c(1,1))
verboseScatterplot(abs(geneModuleMembership[moduleGenes, column]),
                   abs(geneTraitSignificance[moduleGenes, 1]),
                   xlab = paste("Module Membership in", module, "module"),
                   ylab = "Gene significance for Treatment",main = paste("Module membership vs. gene significance\n"),
                   cex.main = 1.2, cex.lab = 1.2, cex.axis = 1.2, col = module)

# Define variable weight containing the weight column of datTrait
weight = as.data.frame(wg_model$D9_E)
names(weight) = "D9_E"
# names (colors) of the modules
modNames = substring(names(MEs), 3)
geneModuleMembership = as.data.frame(cor(datExpr, MEs, use = "p"))
MMPvalue = as.data.frame(corPvalueStudent(as.matrix(geneModuleMembership), nSamples))
names(geneModuleMembership) = paste("MM", modNames, sep="");names(MMPvalue) = paste("p.MM", modNames, sep="")
geneTraitSignificance = as.data.frame(cor(datExpr, weight, use = "p"))
GSPvalue = as.data.frame(corPvalueStudent(as.matrix(geneTraitSignificance), nSamples))
names(geneTraitSignificance) = paste("GS.", names(weight), sep="");names(GSPvalue) = paste("p.GS.", names(weight), sep="");
module = "orangered4"
column = match(module, modNames)
moduleGenes = moduleColors==module
sizeGrWindow(7, 7);par(mfrow = c(1,1))
verboseScatterplot(abs(geneModuleMembership[moduleGenes, column]),
                   abs(geneTraitSignificance[moduleGenes, 1]),
                   xlab = paste("Module Membership in", module, "module"),
                   ylab = "Gene significance for Treatment",main = paste("Module membership vs. gene significance\n"),
                   cex.main = 1.2, cex.lab = 1.2, cex.axis = 1.2, col = module)
```

```{r}
# Define variable weight containing the weight column of datTrait
weight = as.data.frame(wg_model$D9_E)
names(weight) = "Treatment"
# names (colors) of the modules
modNames = substring(names(MEs), 3)
geneModuleMembership = as.data.frame(cor(datExpr, MEs, use = "p"))
MMPvalue = as.data.frame(corPvalueStudent(as.matrix(geneModuleMembership), nSamples))
names(geneModuleMembership) = paste("MM", modNames, sep="");names(MMPvalue) = paste("p.MM", modNames, sep="")
geneTraitSignificance = as.data.frame(cor(datExpr, weight, use = "p"))
GSPvalue = as.data.frame(corPvalueStudent(as.matrix(geneTraitSignificance), nSamples))
names(geneTraitSignificance) = paste("GS.", names(weight), sep="");names(GSPvalue) = paste("p.GS.", names(weight), sep="");
module = "violet"
column = match(module, modNames)
moduleGenes = moduleColors==module
sizeGrWindow(7, 7);par(mfrow = c(1,1))
verboseScatterplot(abs(geneModuleMembership[moduleGenes, column]),
                   abs(geneTraitSignificance[moduleGenes, 1]),
                   xlab = paste("Module Membership in", module, "module"),
                   ylab = "Gene significance for Treatment",main = paste("Module membership vs. gene significance\n"),
                   cex.main = 1.2, cex.lab = 1.2, cex.axis = 1.2, col = module)


```

